import type { Assessment } from "./types";

export const initialAssessments: Assessment[] = [
  {
    id: "ASM-001",
    participantId: "PT-001",
    participantName: "Juan Dela Cruz",
    training: "Computer Systems Servicing NC II",
    batch: "CSS-NCII-2026-01",
    trainer: "Maria Santos",
    assessment: "CSS NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-15",
    score: 92,
    passingScore: 75,
    result: "Passed",
    status: "Completed",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Successfully completed the final assessment.",
  },

  {
    id: "ASM-002",
    participantId: "PT-002",
    participantName: "Maria Garcia",
    training: "Computer Systems Servicing NC II",
    batch: "CSS-NCII-2026-01",
    trainer: "Maria Santos",
    assessment: "CSS NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-15",
    score: 84,
    passingScore: 75,
    result: "Passed",
    status: "Completed",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Participant met the passing requirement.",
  },

  {
    id: "ASM-003",
    participantId: "PT-003",
    participantName: "Pedro Reyes",
    training: "Computer Systems Servicing NC II",
    batch: "CSS-NCII-2026-01",
    trainer: "Maria Santos",
    assessment: "CSS NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-15",
    score: 68,
    passingScore: 75,
    result: "Failed",
    status: "Retake Required",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Participant did not meet the passing score.",
  },

  {
    id: "ASM-004",
    participantId: "PT-004",
    participantName: "Ana Mendoza",
    training: "Computer Systems Servicing NC II",
    batch: "CSS-NCII-2026-01",
    trainer: "Maria Santos",
    assessment: "CSS NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-16",
    score: null,
    passingScore: 75,
    result: "Pending",
    status: "Pending",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Result is awaiting trainer submission.",
  },

  {
    id: "ASM-005",
    participantId: "PT-005",
    participantName: "Mark Villanueva",
    training: "Web Development Fundamentals",
    batch: "WEB-DEV-2026-02",
    trainer: "John Cruz",
    assessment: "Web Development Final Project",
    type: "Final Project",
    date: "2026-08-14",
    score: 89,
    passingScore: 75,
    result: "Passed",
    status: "Completed",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Final project successfully completed.",
  },

  {
    id: "ASM-006",
    participantId: "PT-006",
    participantName: "Sofia Ramos",
    training: "Web Development Fundamentals",
    batch: "WEB-DEV-2026-02",
    trainer: "John Cruz",
    assessment: "Web Development Final Project",
    type: "Final Project",
    date: "2026-08-14",
    score: 72,
    passingScore: 75,
    result: "Failed",
    status: "Retake Scheduled",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: "2026-08-25",
    retakeTime: "09:00",
    retakeVenue: "Computer Laboratory 1",
    remarks:
      "Retake scheduled after initial failed assessment.",
  },

  {
    id: "ASM-007",
    participantId: "PT-007",
    participantName: "Daniel Flores",
    training: "Electrical Installation NC II",
    batch: "EIM-NCII-2026-01",
    trainer: "Kevin Santos",
    assessment: "EIM NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-16",
    score: null,
    passingScore: 75,
    result: "Pending",
    status: "Pending",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Assessment is currently in progress.",
  },

  {
    id: "ASM-008",
    participantId: "PT-008",
    participantName: "Rachel Cruz",
    training: "Electrical Installation NC II",
    batch: "EIM-NCII-2026-01",
    trainer: "Kevin Santos",
    assessment: "EIM NC II Final Assessment",
    type: "Final Assessment",
    date: "2026-08-16",
    score: 81,
    passingScore: 75,
    result: "Passed",
    status: "Completed",
    attempts: 1,
    maxAttempts: 3,
    retakeDate: null,
    retakeTime: null,
    retakeVenue: null,
    remarks:
      "Passed and submitted by trainer.",
  },
];