"use client";

import {
  useEffect,
  useState,
} from "react";

import type {
  LearningModule,
} from "@repo/types";

interface LearningModuleFormModalProps {
  open: boolean;
  mode: "create" | "edit";
  module?: LearningModule | null;

  learningMaterialId: string;

  loading?: boolean;

  onClose: () => void;

  onSubmit: (data: {
    learningMaterialId: string;
    title: string;
    description: string;
  }) => void;
}

export default function LearningModuleFormModal({
  open,
  mode,
  module,
  learningMaterialId,
  loading = false,
  onClose,
  onSubmit,
}: LearningModuleFormModalProps) {
  const isCreate = mode === "create";

  const [
    title,
    setTitle,
  ] = useState("");

  const [
    description,
    setDescription,
  ] = useState("");

  /**
   * ============================================================
   * LOAD FORM DATA
   * ============================================================
   */
  useEffect(() => {
    if (!open) {
      return;
    }

    /**
     * EDIT MODE
     *
     * Load the existing module title and description.
     *
     * ModuleNumber and DisplayOrder are NOT edited here.
     * Backend/database is responsible for those values.
     */
    if (module && mode === "edit") {
      setTitle(
        module.title ?? "",
      );

      setDescription(
        module.description ?? "",
      );

      return;
    }

    /**
     * CREATE MODE
     *
     * Start with an empty title and description.
     *
     * ModuleNumber and DisplayOrder will be
     * automatically generated by the backend.
     */
    if (mode === "create") {
      setTitle("");
      setDescription("");
    }
  }, [
    open,
    mode,
    module,
  ]);

  if (!open) {
    return null;
  }

  /**
   * ============================================================
   * SUBMIT
   * ============================================================
   */
  function handleSubmit(
    event: React.FormEvent<HTMLFormElement>,
  ) {
    event.preventDefault();

    if (!learningMaterialId) {
      return;
    }

    if (!title.trim()) {
      return;
    }

    onSubmit({
      learningMaterialId,

      title:
        title.trim(),

      description:
        description.trim(),
    });
  }

  return (
    <div className="fixed inset-0 z-999 flex items-center justify-center bg-black/40 p-4">
      <div className="w-full max-w-lg rounded-2xl bg-white shadow-xl">
        {/* ======================================================
            HEADER
        ====================================================== */}

        <div className="border-b px-6 py-4">
          <h2 className="text-lg font-semibold text-gray-900">
            {isCreate
              ? "Create Learning Module"
              : "Edit Learning Module"}
          </h2>

          <p className="mt-1 text-sm text-gray-500">
            {isCreate
              ? "Create a module for this learning material."
              : "Update the selected learning module."}
          </p>
        </div>

        {/* ======================================================
            FORM
        ====================================================== */}

        <form
          onSubmit={handleSubmit}
          className="space-y-5 p-6"
        >
          {/* ====================================================
              AUTOMATIC MODULE INFORMATION
          ==================================================== */}

          {isCreate && (
            <div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3">
              <p className="text-sm font-medium text-[#002b5c]">
                Module numbering is automatic
              </p>

              <p className="mt-1 text-xs leading-5 text-gray-600">
                The system will automatically assign the
                next module number and display order based
                on the existing modules.
              </p>
            </div>
          )}

          {!isCreate && (
            <div className="rounded-xl border border-gray-200 bg-gray-50 px-4 py-3">
              <p className="text-sm font-medium text-gray-700">
                Module number and display order
              </p>

              <p className="mt-1 text-xs leading-5 text-gray-500">
                These values are managed by the system and
                cannot be changed from this form.
              </p>
            </div>
          )}

          {/* ====================================================
              TITLE
          ==================================================== */}

          <div>
            <label
              htmlFor="moduleTitle"
              className="mb-1.5 block text-sm font-medium text-gray-700"
            >
              Title
            </label>

            <input
              id="moduleTitle"
              type="text"
              value={title}
              onChange={(event) =>
                setTitle(
                  event.target.value,
                )
              }
              placeholder="Enter module title"
              className="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-gray-400 focus:ring-1 focus:ring-gray-200"
              disabled={loading}
            />
          </div>

          {/* ====================================================
              DESCRIPTION
          ==================================================== */}

          <div>
            <label
              htmlFor="moduleDescription"
              className="mb-1.5 block text-sm font-medium text-gray-700"
            >
              Description
            </label>

            <textarea
              id="moduleDescription"
              value={description}
              onChange={(event) =>
                setDescription(
                  event.target.value,
                )
              }
              placeholder="Enter module description"
              rows={4}
              className="w-full resize-none rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-gray-400 focus:ring-1 focus:ring-gray-200"
              disabled={loading}
            />
          </div>

          {/* ====================================================
              ACTIONS
          ==================================================== */}

          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={loading}
              className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={
                loading ||
                !learningMaterialId ||
                !title.trim()
              }
              className="rounded-xl bg-[#191c1e] px-5 py-2.5 text-sm font-semibold text-white hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {loading
                ? "Saving..."
                : isCreate
                  ? "Create Module"
                  : "Save Changes"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}